version: "3.9"

services:
  php74:
    container_name: laravel-clickhouse-php74
    image: laravel-clickhouse-php74
    build:
      context: ./
      dockerfile: ./.docker/php74/Dockerfile
    restart: unless-stopped
    depends_on:
      - clickhouse
    working_dir: /app
    volumes:
      - ./:/app
      - ./.docker/php74/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - laravel-clickhouse

  php82:
    container_name: laravel-clickhouse-php82
    image: laravel-clickhouse-php82
    build:
      context: ./
      dockerfile: ./.docker/php82/Dockerfile
    restart: unless-stopped
    depends_on:
      - clickhouse
    working_dir: /app
    volumes:
      - ./:/app
      - ./.docker/php82/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - laravel-clickhouse

  clickhouse:
    container_name: laravel-clickhouse-clickhouse
    image: yandex/clickhouse-server:21.8-alpine
    volumes:
      - ./.docker-volume-clickhouse:/var/lib/clickhouse
      - ./.docker/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./.docker/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    healthcheck:
      test: wget --spider -q 0.0.0.0:8123/ping
      interval: 5s
      timeout: 3s
      retries: 5
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - laravel-clickhouse

volumes:
  .docker-volume-clickhouse:
    driver: local

networks:
  laravel-clickhouse:
    driver: bridge
